const types = {
  FETCH_JWT: 'FETCH_JWT',
  SET_TOKEN: 'SET_TOKEN',
  SET_FETCH_JWT_ERROR: 'SET_FETCH_JWT_ERROR',
  SET_LOGIN_IS_WAITING: 'SET_LOGIN_IS_WAITING',
  FETCH_CHANNELS: 'FETCH_CHANNELS',
  ADD_CHANNEL: 'ADD_CHANNEL',
  SET_FETCH_CHANNELS_ERROR: 'SET_FETCH_CHANNELS_ERROR',
};
export default types;
